### ISSUE TITLE
[BUG] Whitespaces do not show in the posts 

### ISSUE THREAD

**Issue by parazeeknova** [parazeeknova/zephyr#18]
When multiline whitespaces are used, the text in the posts does not have spaces between lines and instead curate it in one line.

**Comment by NewtonFernandis** [comment]
Hey @parazeeknova , Can I take this up?

**Comment by parazeeknova** [comment]
Hey @parazeeknova , Can I take this up?

Sure, go for it :)

**Comment by parazeeknova** [comment]
Sure, go for it :)

**Comment by NewtonFernandis** [comment]
Let me know if it needs any changes

**Comment by parazeeknova** [comment]
![Whitespace](https://github.com/user-attachments/assets/3029a7f1-8148-4581-9c6c-064566f64592)

Works as intended, thanks @NewtonFernandis :)
