### ISSUE TITLE
[BUG] Aura Calculation for user and posts do not work and state of the button for upvote or downvote does not save

### ISSUE THREAD

**Issue by parazeeknova** [parazeeknova/zephyr#22]
The current aura calculation for the user does not work; each upvote for a user results in +1 aura, a downvote results in -1 aura, and the user's commutative aura is displayed in their profile.
Also, button state is not saved after a refresh for an upvote or downvote (it is reset).

Create a feature tag in Issues to suggest additional aura 🔥 implementations.

**Comment by NewtonFernandis** [comment]
Hey @parazeeknova, I will take this up 👍

**Comment by parazeeknova** [comment]
Sure @NewtonFernandis :)

**Comment by parazeeknova** [comment]
@NewtonFernandis This issue has been fixed and is now working as intended, so closing it. You can search for other similar issues :)
